### ISSUE TITLE
est_pred_ud.m wrong for loop

### ISSUE THREAD

**Issue by happain** [motoq/bierman#1]
[https://github.com/motoq/bierman/blob/master/src/est_pred_ud.m](url)
  for ii = n: -1 :1
    c = Dtmp*A(:,ii);
    D(ii,ii) = A(:,ii)'*c;
    d = c/D(ii,ii);
    for jj = 1:(ii-1)
      U(jj,ii) = A(:,jj)'*d;
      A(:,jj) = A(:,jj) - U(jj,ii)*A(:,ii);
    end
  end
line 59 for jj = 1:n maybe should midofy as for jj = 1:(ii-1)

**Comment by motoq** [comment]
Thanks again.  I just pushed this update.
