### ISSUE TITLE
est_upd_ud.m calculate b is wrong

### ISSUE THREAD

**Issue by happain** [motoq/bierman#2]
[https://github.com/motoq/bierman/blob/master/src/est_upd_ud.m](url)
a = U'*a';
b = D*U'*a;
maybe should as follow:
a = U'*a';
b = D*a;
book statistical orbit determination page 350 F=U'H', V=DF

**Comment by motoq** [comment]
Great catch happain - I'll push the update soon.  It looks like I accidentally double counted U' when reading Bierman's comments vs. the pseudo code from page 101 of his book.

**Comment by motoq** [comment]
pushed fix
